'use strict';
const $=id=>document.getElementById(id),KEY='madar-exercises-v1';
const DEFAULTS={title:'استكشف علامات الغروب',allowBack:true,questionSeconds:0,totalSeconds:0,advance:'manual',delay:5,feedback:'immediate',hints:true,confidence:true,preserve:true,shuffle:false};
const SEED=[{id:'sunset',version:2,type:'sun',title:'اضبط مشهد الغروب',skill:'تمييز غياب قرص الشمس',instruction:'حرّك الشمس حتى يغيب القرص كاملًا تحت الأفق، ثم أكد اختيارك.',target:-49,tolerance:22,hint:'راقب الحافة العليا للقرص: المطلوب غياب القرص كاملًا تحت الأفق.',explanation:'علامة الغروب غياب قرص الشمس كاملًا. وجود جزء منه فوق الأفق يعني أن الغروب لم يكتمل.'},{id:'horizon',version:1,type:'marker',title:'حدد موضع الدليل',skill:'تحديد الأفق في المشهد',instruction:'ضع المؤشر على خط الأفق الذي تقارن به موضع قرص الشمس. انقر أو المس الموضع المناسب.',region:[0,334,800,366],hint:'ابحث عن الخط الفاصل بين السماء والأرض البعيدة، وليس حدود المباني.',explanation:'الأفق هو الخط الذي تبدو عنده السماء ملتقية بالأرض البعيدة في هذا الرسم؛ نستخدمه لمقارنة موضع الشمس.'},{id:'transfer',version:2,type:'quiz',title:'اختبر فهم العلامة',skill:'تطبيق علامة الغروب في موقف جديد',instruction:'تأمل موضع الشمس في المشهد أمامك، ثم اختر الاستنتاج الصحيح.',sceneHeight:10,choices:['اكتمل الغروب','لم يكتمل الغروب','لا علاقة لقرص الشمس بالغروب'],question:'بقيت الحافة العليا للشمس ظاهرة فوق الأفق. ماذا تستنتج؟',answer:1,hint:'ميّز بين بدء اختفاء القرص واختفائه كاملًا.',explanation:'ما دام جزء من القرص ظاهرًا فوق الأفق، لم يكتمل غروب الشمس.'}];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}
state=state&&Array.isArray(state.tasks)&&Array.isArray(state.attempts)?state:{guest:crypto.randomUUID(),tasks:structuredClone(SEED),attempts:[],events:[]};state.events||=[];state.sessions||=[];state.settings={...DEFAULTS,...state.settings};
for(const seed of SEED){const old=state.tasks.find(t=>t.id===seed.id&&t.title===seed.title&&t.version<seed.version);if(old)Object.assign(old,seed)}
let current=null,filter='all',run=null,active=null,editing=null,dragging=false;
let storageOkay=true;function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOkay=true;$('storageStatus').hidden=true;return true}catch{storageOkay=false;$('storageStatus').hidden=false;return false}}
function event(type,detail={}){state.events.push({type,at:new Date().toISOString(),session:run?.id||null,task:current?.id||null,...detail});save()}
function page(name){if(run&&!run.finished&&name!=='student'){event('navigation_blocked',{destination:name});$('sessionMessage').textContent='أكمل الجلسة أو أنهها مع حفظ النتائج قبل فتح القسم الآخر.';return}document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='insights'){insights();learningTrends();}if(name==='teacher'){loadEditor();loadSettings()}}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function catalog(){const done=new Set(state.attempts.filter(a=>a.correct&&state.tasks.some(t=>t.id===a.taskId&&t.version===a.version)).map(a=>a.taskId));$('progress').textContent=`${done.size} من ${state.tasks.length} تمارين مكتملة`;$('cards').innerHTML=state.tasks.filter(t=>t.enabled!==false).filter(t=>filter==='all'||(filter==='quiz'?['quiz','multi','truefalse','numeric'].includes(t.type):!['quiz','multi','truefalse','numeric'].includes(t.type))).map(t=>`<article class="card"><span class="icon">${t.type==='sun'?'◒':t.type==='marker'?'⌖':'≡'}</span><p><span class="tag">${['quiz','multi','truefalse','numeric'].includes(t.type)?'أسئلة ومراجعة':'نشاط تطبيقي'}</span></p><h2>${esc(t.title)}</h2><p>${esc(t.skill)}</p><span class="done">${done.has(t.id)?'✓ مكتمل':'جاهز للتجربة'}</span><button data-start="${esc(t.id)}">تجربة هذا التمرين</button></article>`).join('');$('cards').querySelectorAll('button').forEach(b=>b.onclick=()=>start(b.dataset.start));$('sessionName').textContent=state.settings.title;$('sessionRules').textContent=rules(state.settings);}
function rules(s){return [s.allowBack?'الرجوع للمراجعة متاح؛ الإجابات المؤكدة محفوظة':'الرجوع إلى السؤال السابق غير متاح',s.questionSeconds?`${s.questionSeconds} ثانية لكل سؤال افتراضيًا`:'بلا مدة افتراضية للسؤال',s.totalSeconds?`${s.totalSeconds} ثانية للجلسة`:'بلا حد زمني للجلسة',s.advance==='auto'?'انتقال تلقائي بعد الإجابة':'الانتقال التالي بيدك',s.feedback==='end'?'تظهر الحلول بعد انتهاء الجلسة':'تفسير بعد كل إجابة'].join(' · ')}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));catalog()});
function draw(){const v=Number($('height').value);$('sun').setAttribute('transform',`translate(400 ${350-v})`);$('sun').setAttribute('aria-valuenow',v)}
function sceneSnapshot(){return{sunHeight:Number($('height').value),marker:active?.point?{...active.point}:null}}
function restoreScene(s){$('height').value=s.sunHeight;draw();$('marker').style.display=s.marker?'block':'none';if(s.marker){$('marker').removeAttribute('hidden');$('marker').setAttribute('transform',`translate(${s.marker.x} ${s.marker.y})`)}}
function blank(){return{startedAt:Date.now(),moves:0,hinted:false,confidence:null,choice:null,response:null,point:null,submitted:false,attempt:null,scene:null,deadline:null,elapsedMs:0}}
function start(id){run=null;current=state.tasks.find(t=>t.id===id);if(!current)return;active=blank();renderQuestion(false);event('start',{version:current.version});}
function startSession(){if(!state.tasks.length)return;const tasks=structuredClone(state.tasks.filter(t=>t.enabled!==false));if(!tasks.length)return;if(state.settings.shuffle)for(let i=tasks.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[tasks[i],tasks[j]]=[tasks[j],tasks[i]]}run={id:crypto.randomUUID(),startedAt:Date.now(),finished:false,settings:structuredClone(state.settings),tasks,index:0,slots:tasks.map(()=>null),deadline:state.settings.totalSeconds?Date.now()+state.settings.totalSeconds*1000:null,advanceAt:null};$('sessionSummary').hidden=true;go(0);event('session_start',{settings:run.settings,order:tasks.map(t=>({id:t.id,version:t.version}))});}
$('startSession').onclick=startSession;
function freezeActive(){if(!active)return;active.scene=sceneSnapshot();if(!active.submitted){active.elapsedMs+=Date.now()-active.startedAt;active.startedAt=Date.now()}}
function go(index){if(!run||run.finished||index<0||index>=run.tasks.length)return;if(index<run.index&&!run.settings.allowBack)return;freezeActive();run.advanceAt=null;run.index=index;current=run.tasks[index];const existed=Boolean(run.slots[index]);active=run.slots[index]||(run.slots[index]=blank());active.startedAt=Date.now();if(!existed){const seconds=current.seconds??run.settings.questionSeconds;active.deadline=seconds?Date.now()+seconds*1000:null}renderQuestion(existed);event(existed?'review':'start',{version:current.version,index});tick();}
function renderQuestion(restore){page('student');$('catalog').hidden=true;$('sessionSummary').hidden=true;$('exercise').hidden=false;$('exitNotice').hidden=true;$('sessionMessage').textContent='';const settings=run?.settings||DEFAULTS;
if(restore&&active.scene)restoreScene(active.scene);else{const previousHeight=Number($('height').value);$('height').value=current.sceneHeight??(run&&run.index>0&&settings.preserve?previousHeight:80);draw();$('marker').style.display='none';active.point=null}
$('feedback').hidden=true;$('after').hidden=!active.submitted;$('confirm').disabled=active.submitted;$('hint').disabled=active.submitted;$('hint').hidden=run?!settings.hints:false;$('issue').value=active.attempt?.feedback||'';$('kind').textContent=['quiz','multi','truefalse','numeric'].includes(current.type)?'أسئلة ومراجعة':'نشاط تطبيقي';$('taskTitle').textContent=current.title;$('prompt').textContent=current.instruction;$('objective').textContent='المهارة: '+current.skill;$('sceneWrap').hidden=false;$('quizWrap').hidden=current.type!=='quiz';$('sunControls').hidden=current.type!=='sun';$('height').disabled=active.submitted;$('sceneInstruction').textContent=current.type==='marker'?'انقر على المشهد لوضع المؤشر':current.type==='sun'?'حرّك الشمس أو استخدم شريط الارتفاع':'تأمل المشهد وأجب عن السؤال';$('confidenceLabel').hidden=run?!settings.confidence:false;$('confidence').hidden=$('confidenceLabel').hidden;
document.querySelectorAll('[data-confidence]').forEach(b=>{b.classList.toggle('selected',b.dataset.confidence===active.confidence);b.disabled=active.submitted});
if(current.type==='quiz'){$('quizText').textContent=current.question||current.instruction;$('options').innerHTML=current.choices.map((c,i)=>`<button data-choice="${i}" class="${i===active.choice?'selected':''}" ${active.submitted?'disabled':''}>${esc(c)}</button>`).join('');$('options').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(active.submitted)return;active.choice=Number(b.dataset.choice);active.moves++;$('options').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b))})}
$('sessionBar').hidden=!run;$('retry').hidden=Boolean(run);$('next').textContent=run?(run.index===run.tasks.length-1?'إنهاء الجلسة':'السؤال التالي'):'تمرين آخر';$('previous').hidden=!run||!settings.allowBack;$('previous').disabled=!run||run.index===0;$('previous').textContent='السؤال السابق';$('previous').title='الرجوع للمراجعة دون تعديل الإجابة';$('back').textContent=run?'إنهاء الجلسة مبكرًا':'← العودة إلى التمارين';$('back').disabled=false;
if(active.submitted)showFeedback();else if(active.hinted){$('feedback').hidden=false;$('feedback').className='feedback';$('feedback').textContent=current.hint}
updateSessionBar();}
function updateSessionBar(){if(!run)return;$('questionPosition').textContent=`السؤال ${run.index+1} من ${run.tasks.length}`;$('sessionTitle').textContent=run.settings.title;$('sessionMeter').max=run.tasks.length;$('sessionMeter').value=run.slots.filter(s=>s?.submitted).length;$('sessionPolicy').textContent=run.settings.allowBack?'الرجوع للمراجعة متاح':'الرجوع إلى السابق غير متاح';}
function showFeedback(){const a=active.attempt,settings=run?.settings;$('feedback').hidden=false;$('feedback').className='feedback'+(a.correct?'':' bad');if(settings?.feedback==='end'){$('feedback').className='feedback';$('feedback').textContent=a.status==='timeout'?'انتهى وقت السؤال؛ سُجل دون إجابة مؤكدة.':'حُفظت إجابتك. سيظهر التصحيح بعد انتهاء الجلسة.'}else $('feedback').textContent=(a.status==='timeout'?'انتهى الوقت دون تأكيد الإجابة. ':a.correct?'✓ إجابة صحيحة. ':'تحتاج إلى مراجعة. ')+current.explanation;}
$('height').oninput=()=>{if(active?.submitted)return;draw();if(active)active.moves++};
function scenePoint(e){const r=$('scene').getBoundingClientRect();return{x:(e.clientX-r.left)*800/r.width,y:(e.clientY-r.top)*490/r.height}}
$('scene').onpointerdown=e=>{if(!active||active.submitted)return;const p=scenePoint(e);if(current.type==='sun'){dragging=true;$('scene').setPointerCapture(e.pointerId);setSun(p)}else if(current.type==='marker'){active.point=p;active.moves++;restoreScene({sunHeight:Number($('height').value),marker:p})}};
function setSun(p){$('height').value=Math.max(-70,Math.min(120,350-p.y));draw();active.moves++}
$('scene').onpointermove=e=>{if(dragging&&active&&!active.submitted)setSun(scenePoint(e))};$('scene').onpointerup=()=>dragging=false;$('scene').onpointercancel=()=>dragging=false;
$('sun').onkeydown=e=>{if(current?.type!=='sun'||active?.submitted)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();$('height').value=Number($('height').value)+(['ArrowUp','ArrowRight'].includes(e.key)?1:-1);active.moves++;draw()}};
document.querySelectorAll('[data-confidence]').forEach(b=>b.onclick=()=>{if(active.submitted)return;active.confidence=b.dataset.confidence;document.querySelectorAll('[data-confidence]').forEach(x=>x.classList.toggle('selected',x===b))});
$('hint').onclick=()=>{active.hinted=true;$('feedback').hidden=false;$('feedback').className='feedback';$('feedback').textContent=current.hint;event('hint')};
function submit(timeout=false){if(!active||active.submitted)return false;
if(!timeout&&((!['sun','marker','quiz'].includes(current.type)&&!hasExtraAnswer(current,active.response))||(current.type==='quiz'&&active.choice===null)||(current.type==='marker'&&!active.point))){$('feedback').hidden=false;$('feedback').textContent='حدد إجابتك أولًا ثم أكدها.';return false}
let correct=false,answer=null,ratio=0;if(current.type==='sun'){answer=Number($('height').value);correct=current.range?answer>=current.range[0]&&answer<=current.range[1]:Math.abs(answer-current.target)<=current.tolerance}else if(current.type==='marker'){answer=active.point;const r=current.region;correct=!!answer&&answer.x>=r[0]&&answer.x<=r[2]&&answer.y>=r[1]&&answer.y<=r[3]}else if(current.type==='quiz'){answer=active.choice;correct=answer===current.answer}else{answer=structuredClone(active.response);ratio=gradeExtra(current,answer);correct=ratio===1}if(['sun','marker','quiz'].includes(current.type))ratio=correct?1:0;
freezeActive();active.submitted=true;active.attempt={id:crypto.randomUUID(),sessionId:run?.id||null,questionIndex:run?.index??null,taskId:current.id,version:current.version,skill:current.skill,type:current.type,points:current.points||1,earned:timeout?0:Math.round((current.points||1)*ratio*100)/100,status:timeout?'timeout':'answered',correct:timeout?false:correct,answer:timeout?null:answer,draft:timeout?answer:null,scene:active.scene,confidence:active.confidence,hinted:active.hinted,durationSeconds:Math.round(active.elapsedMs/1000),moves:active.moves,at:new Date().toISOString()};state.attempts.push(active.attempt);event(timeout?'timeout':'submit',{attempt:active.attempt.id});renderQuestion(true);
if(run){updateSessionBar();if(timeout)run.advanceAt=Date.now()+1500;else if(run.settings.advance==='auto')run.advanceAt=Date.now()+run.settings.delay*1000}return true;}
$('confirm').onclick=()=>{if(run&&((active.deadline&&Date.now()>=active.deadline)||(run.deadline&&Date.now()>=run.deadline))){tick();return}submit()};
function next(){if(run){if(!active.submitted)return;const unanswered=run.slots.findIndex(s=>!s?.submitted);if(unanswered===-1){finish('completed');return}if(run.index+1<run.tasks.length)go(run.index+1);else go(unanswered)}else{const i=state.tasks.findIndex(t=>t.id===current.id);start(state.tasks[(i+1)%state.tasks.length].id)}}
$('next').onclick=next;$('previous').onclick=()=>{if(!run?.settings.allowBack)return;go(run.index-1);$('sessionMessage').textContent='المراجعة لا تعيد وقت السؤال التالي؛ يحتفظ بموعد انتهائه الأصلي.'};
$('retry').onclick=()=>start(current.id);
$('back').onclick=()=>{if(run&&!run.finished){$('exitNotice').hidden=false;return}if(active&&!active.submitted)event('leave',{durationSeconds:Math.round((Date.now()-active.startedAt)/1000),moves:active.moves});showCatalog()};
$('cancelExit').onclick=()=>$('exitNotice').hidden=true;$('confirmExit').onclick=()=>finish('abandoned');
function showCatalog(){run=null;active=null;current=null;$('catalog').hidden=false;$('exercise').hidden=true;$('sessionSummary').hidden=true;catalog();page('student')}
$('returnCatalog').onclick=showCatalog;
$('issue').onchange=()=>{if(active?.attempt){active.attempt.feedback=$('issue').value;event('feedback',{attempt:active.attempt.id,value:$('issue').value})}};
function formatTime(seconds){return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`}
function tick(){if(!run||run.finished)return;const now=Date.now();if(run.deadline&&now>=run.deadline){if(active&&!active.submitted)submit(true);finish('session_timeout');return}const overdue=run.slots.findIndex(s=>s&&!s.submitted&&s.deadline&&now>=s.deadline);if(overdue!==-1&&overdue!==run.index){go(overdue);return}if(!active.submitted&&active.deadline&&now>=active.deadline){submit(true);return}
$('questionTimer').textContent=active.submitted?'الإجابة محفوظة':active.deadline?'وقت السؤال '+formatTime(Math.max(0,Math.ceil((active.deadline-now)/1000))):'السؤال بلا مؤقت';$('totalTimer').textContent=run.deadline?'وقت الجلسة '+formatTime(Math.max(0,Math.ceil((run.deadline-now)/1000))):'';
$('autoAdvance').hidden=!run.advanceAt;if(run.advanceAt){$('autoAdvance').textContent='انتقال تلقائي خلال '+Math.max(0,Math.ceil((run.advanceAt-now)/1000))+' ثوانٍ';if(now>=run.advanceAt)next()}}
setInterval(tick,200);document.addEventListener('visibilitychange',()=>{if(run&&!run.finished){event(document.hidden?'tab_hidden':'tab_visible');tick()}});
function finish(reason){if(!run||run.finished)return;freezeActive();run.finished=true;run.advanceAt=null;const answered=run.slots.filter(s=>s?.submitted).map(s=>s.attempt);const report={id:run.id,title:run.settings.title,startedAt:new Date(run.startedAt).toISOString(),endedAt:new Date().toISOString(),reason,settings:run.settings,total:run.tasks.length,correct:answered.filter(a=>a.correct).length,answered:answered.filter(a=>a.status==='answered').length,timedOut:answered.filter(a=>a.status==='timeout').length,unanswered:run.tasks.length-answered.length,durationSeconds:Math.round((Date.now()-run.startedAt)/1000),tasks:run.tasks.map(t=>({id:t.id,version:t.version,title:t.title,skill:t.skill})),attemptIds:answered.map(a=>a.id)};state.sessions.push(report);event('session_end',{reason});$('exercise').hidden=true;$('sessionSummary').hidden=false;$('summaryTitle').textContent=reason==='completed'?'اكتملت الجلسة':reason==='session_timeout'?'انتهى وقت الجلسة':'أُنهِيت الجلسة مبكرًا';$('summaryStats').innerHTML=[[report.correct+'/'+report.total,'إجابات صحيحة'],[report.answered,'إجابات مؤكدة'],[report.timedOut,'انتهى وقت السؤال'],[report.unanswered,'لم تُستكمل']].map(([n,l])=>`<div class="stat"><b>${n}</b><small>${l}</small></div>`).join('');$('summaryList').innerHTML=run.tasks.map((t,i)=>{const a=run.slots[i]?.attempt;return `<article class="card"><span class="tag">السؤال ${i+1}</span><h3>${esc(t.title)}</h3><p>${a?a.status==='timeout'?'انتهى الوقت دون تأكيد':a.correct?'✓ إجابة صحيحة':'تحتاج مراجعة':'لم يُستكمل السؤال'}</p><p>${esc(t.explanation)}</p>${a?`<small>المدة ${a.durationSeconds} ثانية · ${a.hinted?'استخدمت تلميحًا':'دون تلميح'} · الثقة: ${esc({high:'عالية',medium:'متوسطة',low:'منخفضة'}[a.confidence]||'لم تحدد')}</small>`:''}</article>`}).join('');$('sessionMessage').textContent='';catalog();save();}
function insights(){const a=state.attempts;$('stats').innerHTML=[[state.sessions.length,'جلسات مسجلة'],[a.filter(x=>x.correct).length,'إجابات صحيحة'],[a.filter(x=>!x.correct&&x.confidence==='high'&&x.status!=='timeout').length,'خطأ مع ثقة عالية'],[a.filter(x=>x.status==='timeout').length,'انتهاء وقت السؤال']].map(([n,l])=>`<div class="stat"><b>${n}</b><small>${l}</small></div>`).join('');const skills=[...new Set(a.map(x=>x.skill))];$('results').innerHTML=skills.length?skills.map(s=>{const x=a.filter(y=>y.skill===s);return `<tr><td>${esc(s)}</td><td>${x.length}</td><td>${x.filter(y=>y.correct).length}</td><td>${x.filter(y=>!y.correct&&y.confidence==='high'&&y.status!=='timeout').length}</td><td>${x.filter(y=>y.hinted).length}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">ابدأ جلسة أو تمرينًا لتظهر النتائج.</td></tr>';$('issues').innerHTML=a.filter(x=>x.feedback).map(x=>`<p>${esc(x.skill)} — ${esc(x.feedback)}</p>`).join('')||'لا توجد ملاحظات بعد.';$('sessionResults').innerHTML=state.sessions.length?state.sessions.map(s=>`<tr><td>${esc(s.title)}</td><td>${esc({completed:'مكتملة',session_timeout:'انتهى الوقت',abandoned:'إنهاء مبكر'}[s.reason]||s.reason)}</td><td>${s.correct}/${s.total}</td><td>${s.durationSeconds} ث</td><td>${s.timedOut}</td><td>${s.unanswered}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">لم تنتهِ جلسة بعد.</td></tr>'}
function learningTrends(){const groups=new Map();for(const a of state.attempts){if(a.status==='timeout')continue;const k=a.taskId+'@'+a.version;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(a)}$('learningTrends').innerHTML=groups.size?[...groups.values()].map(list=>{const first=list[0],last=list.at(-1),task=state.tasks.find(t=>t.id===first.taskId&&t.version===first.version),label=task?.title||first.skill;return `<tr><td>${esc(label)} / ${first.version}</td><td>${list.length}</td><td>${first.correct?'صحيحة':'غير صحيحة'}${first.hinted?' · بتلميح':''}</td><td>${list.length>1?(last.correct?'صحيحة':'غير صحيحة')+(last.hinted?' · بتلميح':''):'لا توجد مقارنة بعد'}</td><td>${Math.round(list.reduce((sum,a)=>sum+a.durationSeconds,0)/list.length)} ث</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">لا توجد إجابات مؤكدة للمقارنة.</td></tr>'}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportResults(){download('madar-attempts.json',{format:'madar-attempts-v2',exportedAt:new Date().toISOString(),guest:state.guest,sessions:state.sessions,attempts:state.attempts,events:state.events})}
$('exportData').onclick=exportResults;$('exportSession').onclick=exportResults;$('clearData').onclick=()=>$('clearNotice').hidden=false;$('cancelClear').onclick=()=>$('clearNotice').hidden=true;$('confirmClear').onclick=()=>{state.attempts=[];state.events=[];state.sessions=[];state.guest=crypto.randomUUID();save();insights();learningTrends();catalog();$('clearNotice').hidden=true};
function fields(){['sun','marker','quiz'].forEach(t=>$(t+'Fields').hidden=$('type').value!==t)}$('type').onchange=fields;
function loadEditor(id){$('editSelect').innerHTML=state.tasks.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('');fill(state.tasks.find(x=>x.id===id)||state.tasks[0]);renderOrder()}
function fill(t){editing=t?.id||null;$('editSelect').value=t?.id||'';$('type').value=t?.type||'sun';$('title').value=t?.title||'';$('skill').value=t?.skill||'';$('instruction').value=t?.instruction||'';$('target').value=t?.target??-49;$('tolerance').value=t?.tolerance??22;$('region').value=(t?.region||[0,334,800,366]).join(',');$('choices').value=(t?.choices||[]).join('\n');$('answer').value=(t?.answer??0)+1;$('hintText').value=t?.hint||'';$('explanation').value=t?.explanation||'';$('taskSeconds').value=t?.seconds??'';$('sceneHeight').value=t?.sceneHeight??'';fields()}
$('editSelect').onchange=()=>fill(state.tasks.find(t=>t.id===$('editSelect').value));$('newTask').onclick=()=>fill(null);
function valid(t){if(typeof t.id!=='string'||!['sun','marker','quiz','multi','truefalse','order','match','numeric'].includes(t.type)||!['title','skill','instruction','hint','explanation'].every(k=>typeof t[k]==='string'&&t[k].trim())||!Number.isInteger(t.version)||t.version<1)return false;if(!validMeta(t))return false;if(!['sun','marker','quiz'].includes(t.type))return validExtra(t);if(t.seconds!==undefined&&(!Number.isInteger(t.seconds)||t.seconds<0||t.seconds>3600))return false;if(t.sceneHeight!==undefined&&(!Number.isFinite(t.sceneHeight)||t.sceneHeight< -70||t.sceneHeight>120))return false;if(t.type==='sun'&&t.range!==undefined)return validExtra(t);if(t.type==='sun')return Number.isFinite(t.target)&&t.target>=-70&&t.target<=120&&Number.isFinite(t.tolerance)&&t.tolerance>=1&&t.tolerance<=40;if(t.type==='marker')return Array.isArray(t.region)&&t.region.length===4&&t.region.every(Number.isFinite)&&t.region[0]>=0&&t.region[1]>=0&&t.region[2]<=800&&t.region[3]<=490&&t.region[0]<t.region[2]&&t.region[1]<t.region[3];return Array.isArray(t.choices)&&t.choices.length>=2&&t.choices.every(c=>typeof c==='string'&&c.trim())&&new Set(t.choices).size===t.choices.length&&Number.isInteger(t.answer)&&t.answer>=0&&t.answer<t.choices.length}
function readTask(){const old=state.tasks.find(t=>t.id===editing),t={id:editing||crypto.randomUUID(),version:(old?.version||0)+1,type:$('type').value,title:$('title').value.trim(),skill:$('skill').value.trim(),instruction:$('instruction').value.trim(),hint:$('hintText').value.trim(),explanation:$('explanation').value.trim()};if($('taskSeconds').value!=='')t.seconds=Number($('taskSeconds').value);if($('sceneHeight').value!=='')t.sceneHeight=Number($('sceneHeight').value);if(t.type==='sun'){t.target=Number($('target').value);t.tolerance=Number($('tolerance').value)}if(t.type==='marker')t.region=$('region').value.split(',').map(Number);if(t.type==='quiz'){t.choices=$('choices').value.split('\n').map(x=>x.trim()).filter(Boolean);t.answer=Number($('answer').value)-1;t.question=t.instruction}return t}
function saveTask(){const t=readTask();if(!valid(t)){$('builderStatus').textContent='راجع نطاق المشهد والمدة والخيارات والإجابة الصحيحة.';return null}const old=state.tasks.find(x=>x.id===editing);if(old)state.tasks[state.tasks.indexOf(old)]=t;else state.tasks.push(t);editing=t.id;save();catalog();return t}
$('builder').onsubmit=e=>{e.preventDefault();const t=saveTask();if(t)start(t.id)};$('saveTask').onclick=()=>{const t=saveTask();if(t){loadEditor(t.id);$('builderStatus').textContent='حُفظ السؤال ضمن الجلسة.'}};
function renderOrder(){$('questionOrder').innerHTML=state.tasks.map((t,i)=>`<div class="order-row"><span>${i+1}. ${esc(t.title)}</span><button type="button" class="secondary" data-up="${i}" ${i===0?'disabled':''} aria-label="تقديم ${esc(t.title)}">↑</button><button type="button" class="secondary" data-down="${i}" ${i===state.tasks.length-1?'disabled':''} aria-label="تأخير ${esc(t.title)}">↓</button></div>`).join('');$('questionOrder').querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.up??b.dataset.down),j=b.dataset.up!==undefined?i-1:i+1;[state.tasks[i],state.tasks[j]]=[state.tasks[j],state.tasks[i]];save();renderOrder();catalog()})}
function loadSettings(){const s=state.settings;$('settingTitle').value=s.title;['allowBack','hints','confidence','preserve','shuffle'].forEach(k=>$('setting_'+k).checked=s[k]);['questionSeconds','totalSeconds','advance','delay','feedback'].forEach(k=>$('setting_'+k).value=s[k]);}
function validSettings(s){return typeof s.title==='string'&&s.title.trim()&&['allowBack','hints','confidence','preserve','shuffle'].every(k=>typeof s[k]==='boolean')&&Number.isInteger(s.questionSeconds)&&s.questionSeconds>=0&&s.questionSeconds<=3600&&Number.isInteger(s.totalSeconds)&&s.totalSeconds>=0&&s.totalSeconds<=14400&&Number.isInteger(s.delay)&&s.delay>=1&&s.delay<=60&&['manual','auto'].includes(s.advance)&&['immediate','end'].includes(s.feedback)}
function saveSettings(){const s={title:$('settingTitle').value.trim()};['allowBack','hints','confidence','preserve','shuffle'].forEach(k=>s[k]=$('setting_'+k).checked);['questionSeconds','totalSeconds','delay'].forEach(k=>s[k]=Number($('setting_'+k).value));['advance','feedback'].forEach(k=>s[k]=$('setting_'+k).value);if(!validSettings(s)){$('settingsStatus').textContent='راجع عنوان الجلسة والمدد.';return false}state.settings=s;save();catalog();$('settingsStatus').textContent='حُفظت إعدادات الجلسة. تُطبق عند بدء جلسة جديدة.';return true}
$('sessionSettings').onsubmit=e=>{e.preventDefault();saveSettings()};
$('previewSession').onclick=()=>{if($('sessionSettings').reportValidity()&&saveSettings())startSession()};
$('exportPack').onclick=()=>download('madar-exercises.json',{format:'madar-exercises-v2',tasks:state.tasks,settings:state.settings});$('importPack').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!['madar-exercises-v1','madar-exercises-v2'].includes(data.format)||!Array.isArray(data.tasks)||!data.tasks.length||data.tasks.length>100||!data.tasks.every(valid)||new Set(data.tasks.map(t=>t.id)).size!==data.tasks.length)throw Error();const settings={...DEFAULTS,...data.settings};if(!validSettings(settings))throw Error();state.tasks=data.tasks;state.settings=settings;save();catalog();loadEditor();loadSettings();$('builderStatus').textContent='تم استيراد الأسئلة وإعدادات الجلسة.'}catch{$('builderStatus').textContent='تعذر الاستيراد؛ الحزمة غير صالحة.'}e.target.value=''};
window.addEventListener('beforeunload',e=>{if(run&&!run.finished){e.preventDefault();e.returnValue=''}});
$('objective').after($('quizWrap'));
// One scrollable question body and a shared action/navigation footer.
const questionPanel=document.querySelector('#exercise aside.task'),questionBody=document.createElement('div');questionBody.className='task-body';while(questionPanel.firstChild)questionBody.append(questionPanel.firstChild);questionPanel.append(questionBody);
const questionFooter=document.createElement('div');questionFooter.className='task-footer';const answerActions=$('confirm').parentElement;answerActions.classList.add('answer-actions');questionFooter.append(answerActions);
const reviewNote=document.createElement('p');reviewNote.className='review-note';reviewNote.textContent='الرجوع للمراجعة؛ الإجابة المؤكدة محفوظة';reviewNote.hidden=true;questionFooter.append(reviewNote);
const taskNav=document.createElement('div');taskNav.className='task-nav';for(const id of ['previous','next','retry']){const oldParent=$(id).parentElement;taskNav.append($(id));if(!oldParent.children.length)oldParent.remove()}questionFooter.append(taskNav);questionPanel.append(questionFooter);
const issueDetails=document.createElement('details');issueDetails.className='question-feedback';const issueSummary=document.createElement('summary');issueSummary.textContent='ملاحظة على السؤال (اختياري)';issueDetails.append(issueSummary);issueDetails.append(document.querySelector('label[for="issue"]'),$('issue'));$('after').replaceChildren(issueDetails);
function syncQuestionLayout(){const height=$('sceneWrap').getBoundingClientRect().height;if(height>0)questionPanel.style.setProperty('--scene-block-height',height+'px');$('next').hidden=!active?.submitted;$('retry').hidden=Boolean(run)||!active?.submitted;$('confirm').hidden=Boolean(active?.submitted);if(active?.submitted)$('hint').hidden=true;reviewNote.hidden=!run||!run.settings.allowBack||!active?.submitted;taskNav.hidden=!active?.submitted&&(!run||!run.settings.allowBack||run.index===0);answerActions.hidden=Boolean(active?.submitted);if(active?.submitted){const overflow=$('feedback').getBoundingClientRect().bottom-questionBody.getBoundingClientRect().bottom;if(overflow>0)questionBody.scrollTop+=overflow+8}}
new ResizeObserver(syncQuestionLayout).observe($('sceneWrap'));
new ResizeObserver(()=>document.body.style.setProperty('--task-footer-space',(questionFooter.getBoundingClientRect().height+16)+'px')).observe(questionFooter);
const originalRenderQuestion=renderQuestion;renderQuestion=function(restore){originalRenderQuestion(restore);document.body.classList.add('in-exercise');questionBody.scrollTop=0;issueDetails.open=false;syncQuestionLayout();if(active?.submitted){const overflow=$('feedback').getBoundingClientRect().bottom-questionBody.getBoundingClientRect().bottom;if(overflow>0)questionBody.scrollTop=overflow+8}};
const originalShowCatalog=showCatalog;showCatalog=function(){document.body.classList.remove('in-exercise');originalShowCatalog()};
const originalFinish=finish;finish=function(reason){originalFinish(reason);document.body.classList.remove('in-exercise')};
const originalPage=page;page=function(name){originalPage(name);if(name!=='student'&&(!run||run.finished))document.body.classList.remove('in-exercise')};
catalog();draw();save();
