// Compact controls and editable public interface copy.
const polishStyle=document.createElement('style');polishStyle.textContent='input[type=range]{direction:rtl!important}#prayerBuilder .settings-grid{align-items:start;gap:12px 18px;grid-template-columns:repeat(auto-fit,minmax(230px,1fr))}#prayerBuilder label{margin:5px 0;font-size:14px}#prayerBuilder input[type=time],#prayerBuilder input[type=number]{width:155px;max-width:100%;padding:8px 10px}#prayerBuilder .inline-note{padding:10px;margin:8px 0;font-size:12px}#prayerBuilder input,#prayerBuilder select{min-height:40px}#prayerBuilder .actions{display:flex;gap:8px}#prayerBuilder .actions button{width:auto;flex:0 1 auto}#prayerBuilder h2{font-size:23px;margin:8px 0}#prayerBuilder>p{margin:8px 0;font-size:14px}.copy-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.copy-grid label{display:grid;gap:7px;font-size:13px}.platform-links{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.platform-links a{color:var(--green);text-decoration:none;border:1px solid var(--line);border-radius:10px;padding:9px 14px;background:white}@media(max-width:650px){#prayerBuilder .settings-grid,.copy-grid{grid-template-columns:1fr}#prayerBuilder .actions button{width:100%}}';document.head.append(polishStyle);
const copyTargets=[];
const eligible='header b,header small,nav [data-page],.studio-head h1,.studio-head p,.studio-head .eyebrow,[data-studio],[data-filter],#catalog .hero h1,#catalog .hero p,#catalog .hero .eyebrow,#insights>h1,#insights>h2,#insights>.eyebrow,#studioGuide h2,#studioGuide p,#prayerBuilder>h2,#prayerBuilder>.eyebrow';
document.querySelectorAll(eligible).forEach((node,i)=>{const key='text-'+i;node.dataset.copyKey=key;copyTargets.push({key,node,original:node.textContent.trim()})});
// The older height tasks retain their grading values. Reverse only the UI scale
// so right means high/daylight, and moving left lowers the sun toward sunset.
const nativeRangeValue=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');
for(const id of ['height','teacherHeight']){const input=$(id);if(!input)continue;const sum=Number(input.min)+Number(input.max),modelValue=Number(nativeRangeValue.get.call(input));Object.defineProperty(input,'value',{configurable:true,get(){return String(sum-Number(nativeRangeValue.get.call(this)))},set(value){nativeRangeValue.set.call(this,String(sum-Number(value)))}});input.value=modelValue;input.setAttribute('dir','rtl')}
const footer=document.querySelector('footer');if(footer){const node=document.createElement('div');node.dataset.copyKey='footer';node.textContent=footer.textContent.trim();footer.replaceChildren(node);copyTargets.push({key:'footer',node,original:node.textContent})}
const assetCopySelector='header strong,header b,header small,#publicBrand,#publicAnnouncement,h1,h2,nav button,footer';
if(window.MADAR_ASSETS)for(const[name,source]of Object.entries(window.MADAR_ASSETS)){if(!name.endsWith('.html'))continue;const doc=new DOMParser().parseFromString(source,'text/html');doc.querySelectorAll(assetCopySelector).forEach((node,i)=>{if(node.textContent.trim())copyTargets.push({key:`asset:${name}:${i}`,node,original:node.textContent.trim(),label:`${name.includes('index')?'الرئيسية':'عرض المواقيت'} · ${node.textContent.trim()}`})})}
function applyCopy(){for(const entry of copyTargets){const value=state.settings.siteText?.[entry.key];entry.node.textContent=typeof value==='string'&&value.trim()?value:entry.original}}
const copyPanel=document.createElement('div');copyPanel.id='siteCopyPanel';copyPanel.className='card';copyPanel.hidden=true;copyPanel.innerHTML='<span class="eyebrow">إدارة واجهة الموقع</span><h2>العناوين والتبويبات والتذييل</h2><p>هذه النصوص تُحفظ في هذا المتصفح وتدخل ضمن حزمة الأسئلة ونسخة الطالب المنشورة.</p><form id="siteCopyForm"><div class="copy-grid"></div><div class="actions"><button>حفظ النصوص</button><button type="button" id="downloadLearnerSite" class="secondary">تنزيل نسخة الطالب للنشر</button></div><p id="siteCopyStatus" role="status"></p></form>';document.querySelector('.studio-tabs').after(copyPanel);
const publicLinkOption=document.createElement('label');publicLinkOption.className='check';publicLinkOption.innerHTML='<input id="publicEducationLink" type="checkbox">إظهار رابط التعليم والتدريب في واجهة العامة';copyPanel.querySelector('.actions').before(publicLinkOption);
const copyTab=document.createElement('button');copyTab.type='button';copyTab.textContent='واجهة الموقع والنشر';copyTab.setAttribute('role','tab');document.querySelector('.studio-tabs').append(copyTab);
function loadCopyForm(){copyPanel.querySelector('.copy-grid').innerHTML=copyTargets.map(e=>`<label>${esc((e.label||e.original).slice(0,70))}<textarea data-copy-field="${e.key}" maxlength="1000">${esc(state.settings.siteText?.[e.key]??e.original)}</textarea></label>`).join('')}
const beforePublicCopyForm=loadCopyForm;loadCopyForm=function(){beforePublicCopyForm();$('publicEducationLink').checked=!!state.settings.publicEducationLink};
const beforeCopyTab=studioTab;studioTab=function(name){beforeCopyTab(name);copyPanel.hidden=true;copyTab.classList.remove('active')};copyTab.onclick=()=>{studioTab('guide');$('studioGuide').hidden=true;copyPanel.hidden=false;copyTab.classList.add('active');document.querySelectorAll('[data-studio]').forEach(b=>b.classList.remove('active'));loadCopyForm()};
$('siteCopyForm').onsubmit=e=>{e.preventDefault();const values={};copyPanel.querySelectorAll('[data-copy-field]').forEach(input=>values[input.dataset.copyField]=input.value.trim());state.settings.siteText=values;applyCopy();$('siteCopyStatus').textContent=save()?'حُفظت النصوص. نزّل نسخة الطالب لتطبيقها على الموقع المنشور.':'تعذر الحفظ على الجهاز؛ صدّر الحزمة للاحتفاظ بالتغييرات.'};
const beforePublicCopySave=$('siteCopyForm').onsubmit;$('siteCopyForm').onsubmit=e=>{state.settings.publicEducationLink=$('publicEducationLink').checked;beforePublicCopySave(e)};
const confirmSiteSave=document.createElement('div');confirmSiteSave.id='siteSaveConfirmation';confirmSiteSave.setAttribute('role','status');confirmSiteSave.setAttribute('aria-live','polite');confirmSiteSave.hidden=true;copyPanel.querySelector('.actions').before(confirmSiteSave);
const siteSaveButton=copyPanel.querySelector('.actions button');siteSaveButton.type='button';siteSaveButton.id='saveSiteText';
function verifiedSiteSave(){const values={};copyPanel.querySelectorAll('[data-copy-field]').forEach(input=>values[input.dataset.copyField]=input.value.trim());const previous=structuredClone(state.settings);state.settings.siteText=values;state.settings.publicEducationLink=$('publicEducationLink').checked;state.settings.siteTextUpdatedAt=new Date().toISOString();let okay=save();if(okay){try{const persisted=JSON.parse(localStorage.getItem(KEY));okay=JSON.stringify(persisted.settings.siteText)===JSON.stringify(values)&&persisted.settings.publicEducationLink===state.settings.publicEducationLink}catch{okay=false}}if(!okay)state.settings=previous;else applyCopy();confirmSiteSave.hidden=false;confirmSiteSave.style.cssText='position:sticky;bottom:12px;padding:14px;border:2px solid '+(okay?'#4a9875':'#b25746')+';background:'+(okay?'#edf6ed':'#fff0ed')+';border-radius:12px;margin:12px 0;z-index:5;line-height:1.8';confirmSiteSave.textContent=okay?'✓ حُفظت الإعدادات على هذا الجهاز، وتم التحقق من حفظها. آخر حفظ: '+new Date().toLocaleTimeString('ar-SA')+' · لتطبيقها على الروابط المنشورة نزّل حزمة الموقع ثم ارفع التحديث.':'تعذر تأكيد الحفظ على هذا المتصفح. لم يُعتمد التغيير؛ صدّر الحزمة للاحتفاظ بالعمل.';$('siteCopyStatus').textContent=confirmSiteSave.textContent;confirmSiteSave.scrollIntoView({block:'center',behavior:'smooth'})}
siteSaveButton.onclick=verifiedSiteSave;$('siteCopyForm').onsubmit=e=>{e.preventDefault();verifiedSiteSave()};
const openAdministratorCopy=copyTab.onclick;copyTab.onclick=()=>{if(window.MADAR_ADMIN)openAdministratorCopy()};
applyCopy();
if(location.hash==='#results')page('insights');
if(location.hash==='#assessment'){page('student');$('startSession').scrollIntoView({block:'center'})}
if(['#session-settings','#reports'].includes(location.hash)){page('teacher');studioTab('settings');if(location.hash==='#reports')setTimeout(()=>$('importLearnerReports')?.scrollIntoView({block:'center'}),0)}
if(location.hash==='#publishing'){page('teacher');copyTab.click()}
const beforeCopyCatalog=catalog;catalog=function(){beforeCopyCatalog();applyCopy()};
function editedAssets(){const assets={...window.MADAR_ASSETS};for(const[name,source]of Object.entries(assets)){if(!name.endsWith('.html'))continue;const doc=new DOMParser().parseFromString(source,'text/html');doc.querySelectorAll(assetCopySelector).forEach((node,i)=>{const value=state.settings.siteText?.[`asset:${name}:${i}`];if(value?.trim())node.textContent=value});assets[name]='<!doctype html>\n'+doc.documentElement.outerHTML}return assets}
const beforeStudentAssets=editedAssets;editedAssets=function(){const assets=beforeStudentAssets();const doc=new DOMParser().parseFromString(assets['docs/index.html'],'text/html');doc.querySelectorAll('a[href*="teacher"]').forEach(a=>a.remove());assets['docs/index.html']='<!doctype html>\n'+doc.documentElement.outerHTML;return assets};
const beforeStudentHome=editedAssets;editedAssets=function(){const assets=beforeStudentHome();const doc=new DOMParser().parseFromString(assets['docs/index.html'],'text/html');doc.getElementById('teacherPath')?.remove();doc.getElementById('teacherTab')?.remove();assets['docs/index.html']='<!doctype html>\n'+doc.documentElement.outerHTML;return assets};
const beforePublicAssets=editedAssets;editedAssets=function(){const assets=beforePublicAssets();for(const[name,source]of Object.entries(assets)){if(!name.endsWith('.html'))continue;const doc=new DOMParser().parseFromString(source,'text/html');if(name==='docs/index.html'){const link=doc.querySelector('.public-education');if(link)link.hidden=!state.settings.publicEducationLink}if(name==='docs/education.html'){doc.getElementById('teacherPath')?.remove();doc.getElementById('teacherTab')?.remove()}assets[name]='<!doctype html>\n'+doc.documentElement.outerHTML}return assets};
const previewSiteButton=document.createElement('button');previewSiteButton.type='button';previewSiteButton.className='secondary';previewSiteButton.textContent='معاينة واجهة العامة بالتعديلات';siteSaveButton.after(previewSiteButton);previewSiteButton.onclick=()=>{const assets=editedAssets(),url=URL.createObjectURL(new Blob([assets['docs/index.html']],{type:'text/html;charset=utf-8'}));window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)};
const links=document.createElement('div');links.className='platform-links';links.innerHTML='<a href="index.html">الرئيسية</a><a href="display.html">عرض مواقيت الصلاة</a>';if(window.MADAR_PACK||location.pathname.endsWith('/exercises.html'))$('catalog').prepend(links);
// A learner build embeds content only; it never contains teacher attempts/events.
$('downloadLearnerSite').onclick=()=>{if(!window.MADAR_SOURCE){$('siteCopyStatus').textContent='افتح النسخة المستقلة في مجلد منصة-مدار؛ تنزيل نسخة الطالب متاح منها.';return}const pack={id:crypto.randomUUID(),tasks:state.tasks.filter(t=>t.enabled!==false),settings:state.settings};if(!pack.tasks.length){$('siteCopyStatus').textContent='أدرج سؤالًا واحدًا على الأقل في الجلسة.';return}const safe=JSON.stringify(pack).replace(/</g,'\\u003c');let html=window.MADAR_SOURCE.replace('<!--COURSE_DATA-->',()=>`<script>window.MADAR_PACK=${safe};window.MADAR_LEARNER=true;<\/script>`);const blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='exercises.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('siteCopyStatus').textContent='تم تنزيل exercises.html بأسئلتك وإعداداتك. استبدله في مجلد docs ثم حدّث المستودع.'};
if(window.MADAR_LEARNER){document.querySelector('[data-page="teacher"]').hidden=true;const beforeLearnerPage=page;page=function(name){if(name==='teacher')return;beforeLearnerPage(name)};if(location.hash==='#teacher')page('student')}
// Store-only ZIP: a single download contains the complete static student site.
function siteZip(files){const encode=new TextEncoder(),parts=[],central=[];let offset=0;function crc(bytes){let c=0xffffffff;for(const byte of bytes){c^=byte;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}function header(size){const a=new Uint8Array(size);return[a,new DataView(a.buffer)]}for(const[name,text]of Object.entries(files)){const n=encode.encode(name),body=encode.encode(text),sum=crc(body),[h,v]=header(30+n.length);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,sum,true);v.setUint32(18,body.length,true);v.setUint32(22,body.length,true);v.setUint16(26,n.length,true);h.set(n,30);parts.push(h,body);const[c,cv]=header(46+n.length);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,sum,true);cv.setUint32(20,body.length,true);cv.setUint32(24,body.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);c.set(n,46);central.push(c);offset+=h.length+body.length}const size=central.reduce((s,p)=>s+p.length,0),[end,ev]=header(22);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,central.length,true);ev.setUint16(10,central.length,true);ev.setUint32(12,size,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'})}
const zipSiteButton=document.createElement('button');zipSiteButton.type='button';zipSiteButton.className='secondary';zipSiteButton.textContent='تنزيل الموقع كاملًا للنشر (ZIP)';$('downloadLearnerSite').after(zipSiteButton);
zipSiteButton.onclick=()=>{if(!window.MADAR_ASSETS||!window.MADAR_SOURCE){$('siteCopyStatus').textContent='افتح teacher.html في مجلد منصة-مدار لاستخدام التصدير الكامل.';return}const tasks=state.tasks.filter(t=>t.enabled!==false);if(!tasks.length){$('siteCopyStatus').textContent='أدرج سؤالًا واحدًا على الأقل.';return}const pack={id:crypto.randomUUID(),tasks,settings:state.settings},html=window.MADAR_SOURCE.replace('<!--COURSE_DATA-->',()=>`<script>window.MADAR_PACK=${JSON.stringify(pack).replace(/</g,'\\u003c')};window.MADAR_LEARNER=true;<\/script>`),files={...editedAssets(),'docs/exercises.html':html,'docs/.nojekyll':''},url=URL.createObjectURL(siteZip(files)),a=document.createElement('a');a.href=url;a.download='madar-student-site.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('siteCopyStatus').textContent='نزّلت حزمة الطالب كاملة: الرئيسية، عرض المواقيت، التمارين والنتائج. لا تتضمن بيانات محاولاتك أو لوحة التأليف.'};
// Offline collection: import learner reports explicitly, without pretending to sync.
window.addEventListener('hashchange',()=>{const hash=location.hash;if(hash==='#results')page('insights');else if(hash==='#assessment'){page('student');$('startSession').scrollIntoView({block:'center'})}else if(['#session-settings','#reports'].includes(hash)){page('teacher');studioTab('settings');if(hash==='#reports')$('importLearnerReports')?.scrollIntoView({block:'center'})}else if(hash==='#publishing'){page('teacher');copyTab.click()}});
const importedReports=document.createElement('div');importedReports.className='card';importedReports.innerHTML='<h2>تجميع تقارير المتعلمين</h2><p>ينزّل المتعلم سجل البيانات من النتائج، ثم تستورد ملفات JSON هنا. التجميع يدوي على هذا الجهاز، ولا توجد مزامنة تلقائية.</p><label>استيراد تقارير المتعلمين<input id="importLearnerReports" type="file" accept="application/json,.json" multiple></label><p id="reportImportStatus" role="status"></p><div id="importedReportSummary"></div><button id="downloadFinalReport" class="secondary">تنزيل التقرير المجمع</button>';$('studioSettings').append(importedReports);
function reportSummaryHtml(){const reports=state.reportImports||[],rows=reports.map(r=>{const attempts=r.attempts,correct=attempts.filter(a=>a.correct).length;return`<tr><td>${esc(r.guest)}</td><td>${attempts.length}</td><td>${correct}</td><td>${attempts.length?Math.round(correct/attempts.length*100):0}%</td><td>${attempts.filter(a=>a.hinted).length}</td></tr>`}).join('');return`<p>${reports.length} تقارير متعلمين · مؤشرات محاولات، وليست درجة اختبار موحدة.</p><div class="scroll"><table><thead><tr><th>معرف المتعلم</th><th>المحاولات</th><th>الصحيحة</th><th>نسبة صحة المحاولات</th><th>التلميحات</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderImportedReports(){$('importedReportSummary').innerHTML=reportSummaryHtml()}renderImportedReports();
$('importLearnerReports').onchange=async e=>{let added=0,rejected=0;state.reportImports||=[];for(const file of e.target.files){try{if(file.size>5*1024*1024)throw Error();const r=JSON.parse(await file.text());if(r.format!=='madar-attempts-v2'||typeof r.guest!=='string'||!Array.isArray(r.attempts)||r.attempts.length>10000||!r.attempts.every(a=>typeof a.correct==='boolean'&&typeof a.taskId==='string'))throw Error();const clean={guest:r.guest,exportedAt:r.exportedAt,attempts:r.attempts.map(a=>({taskId:a.taskId,version:a.version,skill:String(a.skill||''),correct:a.correct,hinted:!!a.hinted,earned:Number(a.earned)||0,points:Number(a.points)||0,at:a.at,status:a.status}))};const index=state.reportImports.findIndex(x=>x.guest===clean.guest);if(index<0)state.reportImports.push(clean);else state.reportImports[index]=clean;added++}catch{rejected++}}const stored=save();renderImportedReports();$('reportImportStatus').textContent=`تم قبول ${added} ملفات ورفض ${rejected}.${stored?'':' تعذر حفظ التجميع؛ نزّل التقرير الآن.'}`;e.target.value=''};
$('downloadFinalReport').onclick=()=>{const report='<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>تقرير التعلم المجمع</title><style>body{font:16px Tahoma;margin:30px;color:#163e40}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:10px}button{padding:10px}@media print{button{display:none}}</style><h1>تقرير التعلم المجمع</h1><p>تاريخ التصدير: '+esc(new Date().toLocaleString('ar-SA'))+'</p>'+reportSummaryHtml()+'<p>التقارير مستوردة يدويًا. قد تختلف الأسئلة والمحاولات بين المتعلمين؛ لا تُفسر النسب على أنها مقارنة عادلة لاختبار موحد.</p><button onclick="print()">طباعة / حفظ PDF</button></html>',url=URL.createObjectURL(new Blob([report],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='madar-final-report.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
if(window.MADAR_ADMIN){
const adminSection=document.createElement('section');adminSection.id='siteAdministrator';adminSection.innerHTML='<span class="eyebrow">إدارة الموقع — المشرف الرئيسي</span><h1>هوية الموقع وإعدادات النشر</h1><p>هذه شاشة مستقلة عن أدوات المعلم. إعداد الحسابات ومنح الصلاحيات يحتاج خدمة دخول متصلة؛ لا توجد حماية بحسابات في هذه النسخة المحلية.</p><div class="platform-links"><a href="index.html">واجهة العامة</a><a href="education.html">واجهة التعليم</a></div>';
document.querySelector('main').append(adminSection);adminSection.append(copyPanel);copyTab.remove();loadCopyForm();
const adminPage=function(){document.querySelectorAll('main>section').forEach(s=>s.hidden=s!==adminSection);copyPanel.hidden=false};page=adminPage;document.querySelector('header nav').replaceChildren();adminPage();document.title='مدار | المشرف الرئيسي';
}else{copyTab.remove();copyPanel.remove()}
