// A visible authoring path for prayer-time questions, using the existing grading engine.
const prayerBuilder=document.createElement('section');
prayerBuilder.id='prayerBuilder';prayerBuilder.className='card';
prayerBuilder.innerHTML=`<span class="eyebrow">بناء سؤال مواقيت</span><h2>اختر الصلاة وحدد كيف يجيب المتعلم</h2><p>اضبط السؤال والإجابة الصحيحة هنا، ثم افتح معاينة المتعلم. جميع الأوقات في هذا النموذج تعليمية يحددها المعلم.</p><div class="settings-grid"><label>١ · الصلاة<select id="pbPrayer">${Object.entries(PRAYER_NAMES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>٢ · المطلوب من المتعلم<select id="pbMode"><option value="inside">تحريك الزمن إلى أي لحظة داخل وقت الصلاة</option><option value="event">تحريك الزمن إلى بداية وقت الصلاة</option><option value="interval">تحديد بداية وقت الصلاة ونهايته</option><option value="quiz">اختيار اسم الصلاة عند وقت معين</option></select></label><label>٣ · مصدر الإجابة الصحيحة<select id="pbSource"><option value="table">من جدول اليوم المشترك</option><option value="custom">نطاق خاص بهذا السؤال</option></select></label><label>بداية الوقت الصحيح<input id="pbStart" type="time"></label><label>نهاية الوقت الصحيح<input id="pbEnd" type="time"></label><label>هامش قبول الحدود بالدقائق<input id="pbMargin" type="number" min="0" max="60" value="3"></label><label>زمن المشهد عند بدء السؤال<input id="pbInitial" type="time" value="10:00"></label><label>عنوان السؤال<input id="pbTitle"></label></div><label>صياغة المطلوب<textarea id="pbPrompt"></textarea></label><div class="settings-grid"><label class="check"><input id="pbTable" type="checkbox" checked>إظهار جدول مرجعي للطالب</label><label class="check"><input id="pbEnabled" type="checkbox" checked>إدراج السؤال في الجلسة بعد الحفظ</label></div><div id="pbSummary" class="inline-note" role="status"></div><div class="actions"><button id="pbCreate">متابعة إلى المعاينة والتقييم</button><button id="pbTimetable" class="secondary">ضبط جدول اليوم المشترك</button><button id="pbAdvanced" class="secondary">فتح محرر الأنواع الأخرى</button></div><p id="pbStatus" role="status"></p>`;
document.querySelector('.studio-tabs').after(prayerBuilder);
function updatePrayerBuilder(){const key=$('pbPrayer').value,name=PRAYER_NAMES[key],mode=$('pbMode').value,custom=$('pbSource').value==='custom',p=dayPeriods(state.settings.day).prayers.find(x=>x.key===key);if(!custom){$('pbStart').value=minuteString(p.start);$('pbEnd').value=minuteString(p.end)}$('pbStart').disabled=!custom;$('pbEnd').disabled=!custom||mode==='event';$('pbMargin').disabled=!['event','interval'].includes(mode);$('pbSource').disabled=mode==='quiz';if(mode==='quiz')$('pbSource').value='table';if(mode==='quiz')$('pbSource').value='table';const title=mode==='inside'?`اختر لحظة داخل وقت ${name}`:mode==='event'?`حدد بداية وقت ${name}`:mode==='interval'?`حدد بداية وقت ${name} ونهايته`:'ما الصلاة التي يدخل وقتها في هذا المشهد؟';$('pbTitle').value=title;$('pbPrompt').value=mode==='inside'?`حرّك الزمن إلى أي لحظة داخل وقت ${name}، ثم أكد إجابتك.`:mode==='event'?`حرّك الزمن إلى بداية وقت ${name}، ثم أكد إجابتك.`:mode==='interval'?`حدد بداية وقت ${name} ونهايته باستخدام الساعة أو التقاط الزمن من المشهد.`:'اقرأ الساعة والمشهد، ثم اختر اسم الصلاة.';prayerBuilderSummary()}
function prayerBuilderSummary(){const mode=$('pbMode').value,s=$('pbStart').value,e=$('pbEnd').value;$('pbSummary').textContent=mode==='inside'?`التصحيح: أي وقت من ${s} إلى ما قبل ${e} مقبول؛ التحريك داخل الفترة لا يجعل الإجابة خطأ.`:mode==='event'?`التصحيح: البداية ${s} مع هامش ±${$('pbMargin').value} دقيقة.`:mode==='interval'?`التصحيح: البداية ${s} والنهاية ${e}، مع هامش ±${$('pbMargin').value} دقيقة لكل حد.`:`الإجابة الصحيحة: ${PRAYER_NAMES[$('pbPrayer').value]}. يبدأ المشهد داخل وقتها. ${s} — ${e}`}
['pbPrayer','pbMode','pbSource'].forEach(id=>$(id).onchange=updatePrayerBuilder);['pbStart','pbEnd','pbMargin'].forEach(id=>$(id).oninput=prayerBuilderSummary);
function openPrayerBuilder(){studioTab('questions');prayerBuilder.hidden=false;$('studioQuestions').hidden=true;updatePrayerBuilder();prayerBuilder.scrollIntoView({block:'start',behavior:'smooth'})}
$('studioNew').textContent='＋ بناء سؤال';$('studioNew').onclick=async()=>{if(await discard())openPrayerBuilder()};
$('pbAdvanced').onclick=async()=>{if(!await discard())return;prayerBuilder.hidden=true;fill(null);studioTab('questions');step('content')};
$('pbTimetable').onclick=()=>{prayerBuilder.hidden=true;studioTab('settings');daySettings.scrollIntoView({block:'start',behavior:'smooth'})};
$('pbCreate').onclick=async()=>{if(!await discard())return;const key=$('pbPrayer').value,name=PRAYER_NAMES[key],mode=$('pbMode').value,custom=$('pbSource').value==='custom',s=minuteParse($('pbStart').value),e=minuteParse($('pbEnd').value),margin=Number($('pbMargin').value),initial=minuteParse($('pbInitial').value);if(!Number.isInteger(s)||!Number.isInteger(e)||s===e||!Number.isInteger(initial)||!Number.isInteger(margin)||margin<0||margin>60||!$('pbTitle').value.trim()||!$('pbPrompt').value.trim()){$('pbStatus').textContent='أكمل العنوان والمطلوب والأوقات الصحيحة، واجعل نهاية الفترة مختلفة عن بدايتها.';return}const t={id:crypto.randomUUID(),version:1,type:mode==='interval'?'interval':mode==='quiz'?'quiz':'time',title:$('pbTitle').value.trim(),instruction:$('pbPrompt').value.trim(),skill:`تمييز وقت ${name}`,hint:'راجع الساعة والعلامة الظاهرة، واستعن بالجدول إذا كان متاحًا.',explanation:`الإجابة وفق ${custom?'النطاق الذي حدده المعلم':'جدول اليوم المشترك'} لوقت ${name}.`,sceneMode:'day',startMinute:initial,showClock:true,showGuides:false,provideTable:$('pbTable').checked,timeMargin:margin,points:2,enabled:$('pbEnabled').checked,topic:'مواقيت الصلاة',difficulty:'application'};if(mode==='inside'){if(custom)t.timeRange=[s,e];else t.timeRule={kind:'inside',key}}if(mode==='event'){if(custom)t.timeRange=[(s-margin+1440)%1440,(s+margin+1)%1440];else t.timeRule={kind:'event',key}}if(mode==='interval'){if(custom)t.interval=[s,e];else t.intervalRule={kind:'prayer',key};t.partialCredit=true}if(mode==='quiz'){t.choices=Object.values(PRAYER_NAMES);t.answer=Object.keys(PRAYER_NAMES).indexOf(key);t.startMinute=(s+Math.floor((minuteSpan(s,e)-s)/2))%1440}fill(t);editing=null;markDirty();prayerBuilder.hidden=true;studioTab('questions');step('answer');previewStudio();$('builderStatus').textContent='مسودة جاهزة للمعاينة. راجع التفسير والدرجة، ثم احفظ السؤال أو اختر حفظ وتجربة كمتعلم.'};
const beforePrayerStudioTab=studioTab;studioTab=function(name){beforePrayerStudioTab(name);prayerBuilder.hidden=true};
const pbStyle=document.createElement('style');pbStyle.textContent='#prayerBuilder{margin:20px 0;padding:28px;border:2px solid #b8d9cb}#prayerBuilder h2{font-size:26px}#prayerBuilder .settings-grid{grid-template-columns:repeat(2,minmax(0,1fr))}#prayerBuilder .actions{flex-wrap:wrap}#prayerBuilder input,#prayerBuilder select,#prayerBuilder textarea{width:100%;box-sizing:border-box}#prayerBuilder label{display:block;margin:12px 0}#prayerBuilder .check input{width:auto}@media(max-width:650px){#prayerBuilder{padding:18px}#prayerBuilder .settings-grid{grid-template-columns:1fr}}';document.head.append(pbStyle);
openPrayerBuilder();
// A multiple-choice scene is evidence for one question, so keep its time fixed.
const beforePrayerMinute=setDayMinute;setDayMinute=function(minute,interaction=false){if(interaction&&current?.type==='quiz'&&current.sceneMode==='day')return;return beforePrayerMinute(minute,interaction)};
const beforePrayerQuestion=renderQuestion;renderQuestion=function(){beforePrayerQuestion();if(current?.type==='quiz'&&current.sceneMode==='day'){['daySlider','dayTime','dayPlay'].forEach(id=>{if($(id))$(id).disabled=true});document.querySelectorAll('#dayControls button').forEach(b=>b.disabled=true)}};

