// Explain the shared schedule at the point where the author chooses it.
for(const id of ['teacherMinute','daySlider']){const range=$(id);range.setAttribute('dir','rtl');const key=document.createElement('div');key.className='time-direction-key';key.innerHTML='<span>بداية اليوم · الصباح ←</span><span>المساء · نهاية اليوم</span>';range.after(key)}
$('pbSource').options[0].textContent='استخدام مواقيت اليوم الموحدة لجميع الأسئلة';
$('pbSource').options[1].textContent='تحديد أوقات خاصة بهذا السؤال فقط';
const sourceHelp=document.createElement('p');sourceHelp.className='inline-note';sourceHelp.id='pbSourceHelp';$('pbSource').closest('label').append(sourceHelp);
function explainSource(){sourceHelp.textContent=$('pbSource').value==='table'?'تستخدم مواقيت اليوم التي تضبطها مرة واحدة، مثل الظهر 12:00 والعصر 15:30. كل الأسئلة المرتبطة بها تتبع هذا الجدول عند بدء جلسة جديدة.':'تكتب بداية ونهاية مقبولتين لهذا السؤال وحده؛ لا تتغير مواقيت بقية الأسئلة. المشهد يستمر في عرض يومه الموحد، لذلك احرص على توافق الأوقات الخاصة مع العلامة التي تسأل عنها.'}
const beforeSourceUpdate=updatePrayerBuilder;updatePrayerBuilder=function(){beforeSourceUpdate();explainSource()};explainSource();
['pbSource','pbPrayer','pbMode'].forEach(id=>$(id).addEventListener('change',explainSource));
const sceneZoom=document.createElement('dialog');sceneZoom.id='sceneZoom';sceneZoom.innerHTML='<div class="zoom-heading"><b>عرض المشهد المكبّر</b><button type="button" id="closeSceneZoom">إغلاق ✕</button></div><div id="zoomSceneMount"></div>';document.body.append(sceneZoom);
let zoomNode=null,zoomPlaceholder=null,zoomFocus=null;
function expandScene(teacher=false){if(sceneZoom.open)return;zoomNode=teacher?document.querySelector('.studio-preview'):$('sceneWrap');if(!zoomNode)return;zoomFocus=document.activeElement;zoomPlaceholder=document.createComment('scene original position');zoomNode.before(zoomPlaceholder);$('zoomSceneMount').append(zoomNode);sceneZoom.showModal();$('closeSceneZoom').focus()}
sceneZoom.addEventListener('close',()=>{if(zoomNode&&zoomPlaceholder){zoomPlaceholder.replaceWith(zoomNode);zoomNode=null;zoomPlaceholder=null;syncQuestionLayout();zoomFocus?.focus?.()}});
$('closeSceneZoom').onclick=()=>sceneZoom.close();
document.addEventListener('dblclick',e=>{if(e.target.closest('#teacherScene'))expandScene(true);else if(e.target.closest('#scene'))expandScene(false)});
for(const[host,teacher]of [[$('sceneWrap'),false],[document.querySelector('.studio-preview .preview-heading'),true]]){const button=document.createElement('button');button.type='button';button.className='secondary scene-enlarge';button.textContent='⛶ تكبير المشهد';button.title='يمكن أيضًا النقر مرتين على المشهد';button.onclick=()=>expandScene(teacher);host.append(button)}
const zoomStyle=document.createElement('style');zoomStyle.textContent='#sceneZoom{width:min(1200px,94vw);max-width:94vw;max-height:94dvh;border:0;border-radius:18px;padding:16px;box-sizing:border-box;background:#f8faf5;color:var(--ink)}#sceneZoom::backdrop{background:#09292bd9}.zoom-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}#zoomSceneMount .studio-preview{position:static;width:100%;max-height:none}#zoomSceneMount #sceneWrap{width:100%}#zoomSceneMount svg{width:100%;max-height:65dvh;display:block}#zoomSceneMount .preview-question,#zoomSceneMount .quality-box{display:none}.scene-enlarge{margin:8px 12px;font-size:12px;padding:8px 12px}@media(max-width:600px){#sceneZoom{padding:10px;width:96vw;max-width:96vw}.zoom-heading{font-size:14px}}';document.head.append(zoomStyle);
