// East is on the right in this schematic view; the sun progresses toward west.
const shadowOptions=document.createElement('div');shadowOptions.innerHTML='<label class="check"><input id="showHumanShadow" type="checkbox" checked>إظهار ظل الشخص</label><label class="check"><input id="showShadowMarks" type="checkbox">إظهار علامات فيء الزوال والمثل والمثلين</label><p class="field-help">المثل والمثلان يُقاسان زيادةً على فيء الزوال. الأطوال في الرسم تعليمية، وليست قياسًا فلكيًا للموقع.</p>';sceneOptions.append(shadowOptions);
const beforeShadowRead=readTask;readTask=function(){const t=beforeShadowRead();t.showHumanShadow=$('showHumanShadow').checked;t.showShadowMarks=$('showShadowMarks').checked;return t};
const beforeShadowFill=fill;fill=function(t){beforeShadowFill(t);$('showHumanShadow').checked=t?.showHumanShadow!==false;$('showShadowMarks').checked=!!t?.showShadowMarks;previewStudio();studioDirty=false};
['showHumanShadow','showShadowMarks'].forEach(id=>$(id).onchange=()=>{markDirty();previewStudio()});
const beforeShadowMeta=validMeta;validMeta=function(t){return beforeShadowMeta(t)&&['showHumanShadow','showShadowMarks'].every(k=>t[k]===undefined||typeof t[k]==='boolean')};
const humanShape='M-5 0 L-8 -23 L-8 -39 L-15 -25 L-20 -28 L-11 -49 L-6 -52 A9 9 0 1 1 6 -52 L11 -49 L20 -28 L15 -25 L8 -39 L8 -23 L5 0 L0 0 L0 -22 L-1 -22 L-1 0 Z';
function shadowLength(minute,d){const peak=d.dhuhr-d.noonMargin/2,base=d.noonShadow;if(minute<=peak)return base+Math.min(190,Math.pow((peak-minute)/Math.max(1,peak-d.sunrise),1.4)*190);if(minute<=d.asr)return base+64*(minute-peak)/Math.max(1,d.asr-peak);return base+64+126*(minute-d.asr)/Math.max(1,d.maghrib-d.asr)}
const beforeShadowDay=renderDay;renderDay=function(svg,minute,d,teacher=false){const v=beforeShadowDay(svg,minute,d,teacher),g=svg.querySelector('[data-day-layer]');if(!g)return v;const task=teacher?readTask():current||{},show=task.showHumanShadow!==false,marks=!!task.showShadowMarks||dayExplore;
g.querySelectorAll('ellipse[cy="410"],rect[x="364"],path[d="M354 414 H388"]').forEach(n=>n.remove());
for(const[x,name]of [[730,'المشرق'],[70,'المغرب']]){const label=svgNode('text',{x,y:382,'text-anchor':'middle',fill:'#fff1d8','font-size':19,'font-weight':'bold','data-direction':x===730?'east':'west'});label.textContent=name;g.append(label)}
const directionLabel=svgNode('text',{x:400,y:28,'text-anchor':'middle',fill:'#fff1d8','font-size':15});directionLabel.textContent='مسار الشمس: من المشرق إلى المغرب';g.append(directionLabel);
const footX=400,footY=414,sign=v.x<400?1:-1,length=shadowLength(minute,d);if(show&&v.sunVisible){const shadow=svgNode('path',{d:humanShape,transform:`matrix(0 .40 ${-sign*length/70} 0 ${footX} ${footY})`,fill:'#071f25',opacity:.65,'data-human-shadow':'true'});g.append(shadow)}
if(marks&&v.sunVisible){const refs=[[d.noonShadow,'فيء الزوال'],[d.noonShadow+64,'الفيء + طول الشخص'],[d.noonShadow+128,'الفيء + مثلي الطول']];refs.forEach(([distance,name],i)=>{const x=footX+sign*distance;g.append(svgNode('path',{d:`M${x} 391 V434`,stroke:['#edd4a2','#bde6c0','#99d4ec'][i],'stroke-width':2,'stroke-dasharray':'3 3','data-shadow-mark':String(i)}));const label=svgNode('text',{x:footX+sign*(distance+7),y:396-i*18,'text-anchor':sign>0?'start':'end',fill:'#fff1d8','font-size':12});label.textContent=name;g.append(label)});g.append(svgNode('path',{d:`M${footX} 431 H${footX+sign*(d.noonShadow+128)}`,stroke:'#e8d3a1','stroke-width':1}))}
const person=svgNode('path',{d:humanShape,transform:`translate(${footX} ${footY})`,fill:v.sunVisible?'#e1c59c':'#506a77',stroke:'#253e43','stroke-width':1,'data-person':'true'});g.append(person);return{...v,shadow:length}};
// Keep the main question builder's controls equally visible.
const pbShadow=document.createElement('div');pbShadow.className='settings-grid';pbShadow.innerHTML='<label class="check"><input id="pbHumanShadow" type="checkbox" checked>إظهار ظل الشخص</label><label class="check"><input id="pbShadowMarks" type="checkbox">إظهار علامات أطوال الظل</label>';$('pbSummary').before(pbShadow);
const beforeShadowCreate=$('pbCreate').onclick;$('pbCreate').onclick=async()=>{await beforeShadowCreate();if(!prayerBuilder.hidden)return;$('showHumanShadow').checked=$('pbHumanShadow').checked;$('showShadowMarks').checked=$('pbShadowMarks').checked;markDirty();previewStudio()};
if(teacherSvg)previewStudio();
