// Embedded within the scene closure: measurements are excess over noon's shadow.
const metreLayer=document.createElementNS('http://www.w3.org/2000/svg','svg');metreLayer.id='shadowMetreOverlay';metreLayer.setAttribute('aria-label','مقياس الجسم والزيادة بعد فيء الزوال');metreLayer.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:2';document.querySelector('.stage').append(metreLayer);
const metreCounter=node('div','shadow-metre-counter');metreCounter.id='shadowMetreCounter';metreCounter.style.cssText='display:none';document.querySelector('.stage').append(metreCounter);
function metreProject(point,pos){if(!coherentView||focus!=='overview'||!state.follow)return null;const h=+config.height,angle=Solar.mod(pos.az+180,360)*R,dist=Math.max(5.5/zoom,h*(1.25+Math.min(1.5,Math.hypot(pos.vector[0],pos.vector[2])/Math.max(pos.vector[1],.01)))),origin=[Math.sin(angle)*dist,h*.65,Math.cos(angle)*dist],low=-Math.atan(origin[1]/dist),high=Math.max(Math.asin(Solar.apparent(pos).vector[1]),Math.atan((h-origin[1])/dist)),center=(low+high)/2,lens=.5/Math.tan(Math.max(.62,(high-low)/2+.20)),norm=v=>{const m=Math.hypot(...v);return v.map(x=>x/m)},dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],forward=norm([-origin[0],dist*Math.tan(center),-origin[2]]),right=norm(cross([0,1,0],forward)),up=cross(forward,right),v=point.map((x,i)=>x-origin[i]),depth=dot(v,forward);if(depth<=0)return null;const canvas=$('scene');return{x:canvas.clientWidth/2+dot(v,right)*lens*canvas.clientHeight/depth,y:canvas.clientHeight/2-dot(v,up)*lens*canvas.clientHeight/depth};}
function metreSvg(tag,attrs,text){const n=document.createElementNS(metreLayer.namespaceURI,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;metreLayer.append(n);return n}
const measuredMetreDraw=draw;draw=function(){measuredMetreDraw();metreLayer.replaceChildren();const pos=Solar.position(state.date,state.seconds,Solar.cities[state.city]),h=+config.height,n=h*schedule.noonRatio,len=pos.alt>0?h/Math.tan(pos.alt*R):NaN,show=config.hints&&!state.falseDawn&&state.seconds>=schedule.noon&&state.seconds<schedule.maghrib;metreCounter.hidden=!show;metreLayer.style.display=show?'':'none';if(!show)return;const rawExtra=Math.max(0,len-n),extra=Math.abs(rawExtra-h)<.00001?h:Math.abs(rawExtra-2*h)<.00001?2*h:rawExtra,step=Math.floor((extra+.000001)*10)/10;metreCounter.dataset.extra=extra;metreCounter.dataset.height=h;
const text=(point,label,color)=>{if(!point)return;metreSvg('text',{x:point.x+9,y:point.y-5,fill:color,stroke:'#173e40','stroke-width':2,'paint-order':'stroke','font-size':10},label)};
const bottom=metreProject([-.18,0,0],pos),top=metreProject([-.18,h,0],pos);if(bottom&&top){metreSvg('line',{x1:bottom.x,y1:bottom.y,x2:top.x,y2:top.y,stroke:'#b7e5eb','stroke-width':1});text(top,h.toFixed(1)+' م','#fff')}
const horizontal=Math.hypot(pos.vector[0],pos.vector[2]),dir=[-pos.vector[0]/horizontal,-pos.vector[2]/horizontal],start=metreProject([dir[0]*n,0,dir[1]*n],pos),end=metreProject([dir[0]*len,0,dir[1]*len],pos);if(start&&end){metreSvg('line',{x1:start.x,y1:start.y+5,x2:end.x,y2:end.y+5,stroke:extra<h?'#70cfb2':'#bda3ef','stroke-width':1});text(end,step.toFixed(1)+' م','#fff')}};

window.MadarSceneBridge={snapshot(){return{date:state.date,seconds:state.seconds,city:state.city,coordinates:{...Solar.cities[state.city]},height:+config.height,hints:config.hints,zoom,focus,follow:state.follow,view:state.view,coherent:coherentView,mode:state.mode,combine:state.combine,falseDawn:state.falseDawn}},apply(s){if(!s||!Number.isFinite(s.seconds)||s.seconds<0||s.seconds>86399||!/^\d{4}-\d{2}-\d{2}$/.test(s.date))return;liveClock=false;state.playing=false;sequence=null;if(s.coordinates&&Number.isFinite(s.coordinates.lat)&&Number.isFinite(s.coordinates.lon)&&Math.abs(s.coordinates.lat)<=90&&Math.abs(s.coordinates.lon)<=180){Solar.cities.live={...s.coordinates,name:'موقع جلسة الشرح'};state.city='live';if(!$('city').querySelector('[value="live"]'))$('city').append(new Option('موقع جلسة الشرح','live'));$('city').value='live'}state.date=s.date;$('date').value=s.date;config.height=[1,1.7,2].includes(s.height)?s.height:1;config.hints=!!s.hints;zoom=Math.max(1,Math.min(16,s.zoom||1));focus=['overview','sun','body'].includes(s.focus)?s.focus:'overview';coherentView=s.coherent!==false;state.follow=s.follow!==false;state.view=[0,90,180,270,'shadow'].includes(s.view)?s.view:180;state.mode=s.mode==='traveler'?'traveler':'resident';state.combine=s.combine==='delay'?'delay':'advance';recalc(false);state.seconds=s.seconds;state.falseDawn=!!s.falseDawn;$('body-height').value=config.height;$('show-shadow-hints').checked=config.hints;draw()}};
draw();
